- name: Install package and notify SNS
  hosts: webservers
  become: yes
  gather_facts: yes

  tasks:

    - name: Ping host
      ping:
      register: ping_result

    - name: Install httpd
      yum:
        name: httpd
        state: present
      register: pkg_install

    - name: Ensure httpd running
      service:
        name: httpd
        state: started
        enabled: yes
      register: svc_status

    - name: Build SNS message
      set_fact:
        msg: |
          Host: {{ inventory_hostname }}
          Reachable: {{ ping_result.ping | default('unreachable') }}
          Package install changed: {{ pkg_install.changed }}
          Service state: {{ svc_status.state }}

    - name: Send SNS notification
      community.aws.sns:                      # <-- use community.aws.sns instead of aws_sns
        topic_arn: "{{ sns_topic_arn }}"      # note the parameter name is topic_arn here
        message: "{{ msg }}"
        region: ap-south-1
