- name: Install package and notify SNS
  hosts: webservers
  become: yes
  gather_facts: yes

  vars:
    sns_topic_arn: "arn:aws:sns:ap-south-1:212844904937:jenkins-ansible-alerts"

  tasks:

    - name: Ping host
      ping:
      register: ping_result

    - name: Install httpd
      yum:
        name: httpd
        state: present
      register: pkg_install

    - name: Ensure httpd running
      service:
        name: httpd
        state: started
        enabled: yes
      register: svc_status

    - name: Build SNS message
      set_fact:
        msg: |
