---
- name: Create a user and add SSH public key
  hosts: localhost
  become: true
  remote_user: jenkins
  tasks:
    - name: Add a user
      user:
        name: asian
        password: "{{ 'test123' | password_hash('sha512') }}"
        state: present

    - name: Add SSH public key to user
      authorized_key:
        user: asian
        state: present
        key: "{{ lookup('file', '/home/jenkins/id_rsa.pub') }}"
